chore: Add 'unpack-files' script and update bootstrap script to use it

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -16,8 +16,9 @@ LC_ALL=POSIX
 LANGUAGE=POSIX
 export LC_ALL LANGUAGE
 
-# Get physical working directory (absolute path)
+# Get physical working (absolute path) and utilities directory
 worktree="$(CDPATH='' cd -P -- "$(dirname -- "$0")" && pwd -P)" || exit $?
+worktree_utils="${worktree}/utils"
 
 ### Functions
 
@@ -88,80 +89,6 @@ chkstatus_or_exit() {
     unset -v status
 }
 
-# Function to test and extract compressed files
-unpack() {
-    for file in "$@"; do
-        echo "${PROGRAM}: Unpacking ${file} ..."
-        case $file in
-            *.tar)
-                tar tf "$file" >/dev/null \
-                    && tar xpf "$file"
-                chkstatus_or_exit 3
-                ;;
-            *.tar.gz | *.tgz | *.tar.Z)
-                gzip -cd "$file" | tar tf - >/dev/null \
-                    && gzip -cd "$file" | tar xpf -
-                chkstatus_or_exit 3
-                ;;
-            *.tar.bz2 | *.tbz2 | *.tbz)
-                bzip2 -cd "$file" | tar tf - >/dev/null \
-                    && bzip2 -cd "$file" | tar xpf -
-                chkstatus_or_exit 3
-                ;;
-            *.tar.lz | *.tlz)
-                lzip -cd "$file" | tar tf - >/dev/null \
-                    && lzip -cd "$file" | tar xpf -
-                chkstatus_or_exit 3
-                ;;
-            *.tar.xz | *.txz)
-                xz -cd "$file" | tar tf - >/dev/null \
-                    && xz -cd "$file" | tar xpf -
-                chkstatus_or_exit 3
-                ;;
-            *.tar.zst | *.tzst)
-                zstd -cd "$file" | tar -tf - >/dev/null \
-                    && zstd -cd "$file" | tar -xpf -
-                chkstatus_or_exit 3
-                ;;
-            *.zip | *.ZIP)
-                unzip -t "$file" >/dev/null \
-                    && unzip "$file" >/dev/null
-                chkstatus_or_exit 3
-                ;;
-            *.gz)
-                gzip -t "$file" \
-                    && gzip -cd "$file" >"$(basename -- "$file" .gz)"
-                chkstatus_or_exit 3
-                ;;
-            *.bz2)
-                bzip2 -t "$file" \
-                    && bzip2 -cd "$file" >"$(basename -- "$file" .bz2)"
-                chkstatus_or_exit 3
-                ;;
-            *.lz)
-                lzip -t "$file" \
-                    && lzip -cd "$file" >"$(basename -- "$file" .lz)"
-                chkstatus_or_exit 3
-                ;;
-            *.xz)
-                xz -t "$file" \
-                    && xz -cd "$file" >"$(basename -- "$file" .xz)"
-                chkstatus_or_exit 3
-                ;;
-            *.zst)
-                zstd -qt "$file" \
-                    && zstd -cd "$file" >"$(basename -- "$file" .zst)"
-                chkstatus_or_exit 3
-                ;;
-            *)
-                warn "${PROGRAM}: cannot unpack ${file}: Unsupported extension"
-                exit 1
-                ;;
-        esac
-    done
-    unset -v file
-}
-
 # unmount the chroot environment
 demount() {
     warn "Demounting chroot environment ..."
@@ -215,6 +142,16 @@ VENDOR="${VENDOR:=unknown}"
 
 # Compose vendor name adding "-" as suffix
 test -n "$VENDOR" && VENDOR="${VENDOR}-"
+
+# Make sure unpack-files script is available
+if test ! -x "${worktree_utils}/unpack-files"; then
+    warn "${PROGRAM}: Required script 'unpack-files' not found"
+    exit 1
+else # Load the script as a alias
+    alias unpack="${worktree_utils}/unpack-files"
+    alias unpack-files="${worktree_utils}/unpack-files"
+    alias unpack_files="${worktree_utils}/unpack-files"
+fi
 
 ### Parse options
 while getopts :ha:j:ko:s:V name; do
@@ -363,8 +300,11 @@ for file in ${worktree}/stages/${stage}/${@:-??-*}; do
             exit 1
         fi
 
+        # Load the unpack-files script into the chroot environment
+        cp -v "${worktree_utils}/unpack-files" "$LFS/bin"
+
         # Create needed directories if not already created
-        mkdir -pv $LFS/{dev,proc,sys,run}
+        mkdir -pv "$LFS"/{dev,proc,sys,run}
 
         # Setup permissions for the chroot environment
         chown -R root:root "$LFS"
